### ISSUE TITLE
1.0.0 Release Roadmap

### ISSUE THREAD

**Issue by thrawn01** [mailgun/gubernator#75]
## TODO
- [x] Refactor public ABI interface to be consistent with new features. #55
- [x] #50 /v1/HealthCheck dials default EtcdAdvertiseAddress even though only kubernetess is configured
- [x] #72 etcd now correctly identifies IsOwner when updating the peers list
- [x] #57 TestLeakyBucket & TestTokenBucket fails occasionally.
- [ ] #59 Support TLS for GRPC rate-limiter request interface
- [ ] #73 Feature Request: Add ability to configure Gubernator using command-line flags
- [ ] #74 v1.0.0. Performance Review
- [ ] Deploy and testing
